CLASS zcl_pr_email_events DEFINITION PUBLIC ABSTRACT FINAL
  FOR EVENTS OF I_PurchaseRequisitionTP.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_pr_email_events IMPLEMENTATION.
ENDCLASS.
